service: fall-foliage-forecast

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function everyday at 12pm
      - schedule: cron(0 12 * * ? *)
